Relative path refactoring
exponential-ventures/aurum pull request #42
Opened 2020-07-21 13:17 UTC by nathanmartins

2020-07-21 16:38 UTC, rhuankarlus requested changes

2020-07-21 19:09 UTC, rhuankarlus requested changes

2020-07-22 12:44 UTC, nathanmartins commented on aurum/base.py
> +        destination = os.path.join(cons.REPOSITORY_DIR, cons.EXPERIMENTS_METADATA_DIR, f"{theorem.experiment_id}.json")
Resolved.

2020-07-22 13:02 UTC, nathanmartins commented on aurum/commands.py
> +    experiment_dir = os.path.join(cons.REPOSITORY_DIR, cons.EXPERIMENTS_METADATA_DIR)
Resolved.

2020-07-22 13:02 UTC, nathanmartins commented on aurum/commands.py
> +    requirements_metadata_dir = os.path.join(cons.REPOSITORY_DIR, cons.REQUIREMENTS_METADATA_DIR)
Resolved.

2020-07-22 13:09 UTC, nathanmartins commented on aurum/dataset_tracker.py
> +def use_datasets(*args, cwd: str, ):
Good idea, did that, resolved.

2020-07-22 13:17 UTC, merged